config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  mount Decidim::Core::Engine => "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :weblyzard_logs, only: [:create], module: "indices"
end

# Add a simple menu in the admin part
Decidim::Admin::Engine.routes.draw do
  resources :indices, only: [:index], as: "admin_indices" do
    collection do
      resources :sat, except: [:show], as: "admin_indices_sat", controller: :indices_sat do
        resources :feedbacks, except: [:show], controller: :indices_feedbacks
      end
    end
    collection do
      resources :sat_lite, as: "admin_indices_sat_lite", controller: :indices_sat_lite do
        resources :feedbacks, except: [:show], controller: :indices_sat_lite_feedbacks
      end
    end
  end
end

module Decidim
  module Surveys
    class Engine < ::Rails::Engine
      routes do
        resources :surveys do
          get :feedback, on: :member
        end
      end
    end
  end
end

module Decidim
  module SurveySectionsGroup
    class Engine < ::Rails::Engine
      routes do
        resources :survey_sections_group do
          get :export_user_answers, on: :member
        end
      end
    end
  end
end

app/controllers/decidim/admin/indices_sat_controller.rb
# frozen_string_literal: true

module Decidim
  module Admin
    # The controller to handle indices self assessment tool and other customizations
    class IndicesSatController < Decidim::Admin::IndicesApplicationController
      include Paginable
      include TranslatableAttributes

      helper_method :sat_list, :sat_set, :questionnaires

      def index; end

      def new
        @form = form(SatSetForm).instance
      end

      def edit
        @form = form(SatSetForm).from_model(sat_set)
      end

      def create
        @form = form(SatSetForm).from_params(params[:indices_sat_set])
        CreateIndicesSatSet.call(@form) do
          on(:ok) do
            flash[:notice] = "New SAT set created successfully"
            redirect_to admin_indices_sat_index_path
          end

          on(:invalid) do |error|
            flash.now[:alert] = "Error creating the SAT set: #{error}"
            render :new
          end
        end
      end

      def update
        @form = form(SatSetForm).from_params(params[:indices_sat_set])
        UpdateIndicesSatSet.call(@form, sat_set) do
          on(:ok) do
            flash[:notice] = "SAT set updated successfully"
            redirect_to admin_indices_sat_index_path
          end

          on(:invalid) do |error|
            flash.now[:alert] = "Error updating the SAT set: #{error}"
            render :edit
          end
        end
      end

      def destroy
        sat_set.destroy!

        flash[:notice] = "SAT set deleted successfully"

        redirect_to admin_indices_sat_index_path
      end

      private

      def sat_set
        Indices::SatSet.find(params[:id])
      end

      def questionnaires
        return @questionnaires if @questionnaires

        classes = Decidim.participatory_space_manifests.pluck :model_class_name
        components = []
        classes.each do |klass|
          spaces = klass.safe_constantize.where(organization: current_organization)
          spaces.each do |space|
            components.concat Decidim::Component.where(participatory_space: space).pluck(:id)
          end
        end
        surveys = Decidim::Surveys::Survey.where(decidim_component_id: components)
        @questionnaires = Decidim::Forms::Questionnaire.where(questionnaire_for: surveys).map do |questionnaire|
          component = questionnaire.questionnaire_for.component
          [
            "#{translated_attribute(component.participatory_space.title)} :: #{translated_attribute(component.name)}",
            questionnaire.id
          ]
        end
      end

      def sat_list
        paginate(Indices::SatSet).where(type: nil)
      end
    end
  end
end

app/views/decidim/admin/indices_sat/_form.html.erb
<div class="field">
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.select :questionnaire_id, questionnaires %>
</div>

app/views/decidim/admin/indices_sat/edit.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      Edit Self-Assessment tool questionnaire
    </h2>
  </div>

  <%= decidim_form_for(@form, html: { class: "form" }, method: :patch, url: admin_indices_sat_path(sat_set)) do |f| %>
    <div class="card-section">
      <%= render partial: "form", object: f %>

      <div class="button--double form-general-submit">
        <%= f.submit "Save" %>
      </div>
    </div>
  <% end %>
</div>

app/views/decidim/admin/indices_sat/index.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      Self-Assessment tool

      <%= link_to "New Self-Assessment set", new_admin_indices_sat_path, class: "button tiny button--title" %>
    </h2>
  </div>
  <div class="card-section">
    <p>Each Self-assessment tool (SAT) set is linked to a specific questionnaire from a survey component. This questionnaire will be converted to a SAT application:</p>
    <ul>
      <li>After answering the questionnaire, user will receive a calculated feedback according to this specific configuration set</li>
      <li>Feedback is obtained by adding #hashtags in the questionnaire answers (currently only works for single and multiple options type of questions)</li>
      <li>Hashtags will be hidden in the public rendering of the questionnaire</li>
    </ul>

    <h3>Available SAT sets:</h3>
    <% if sat_list.any? %>
      <table class="table-list civicrm-groups">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Questionnaire</th>
            <th>Created</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% sat_list.each do |set| %>
            <tr>
              <td><%= set.id %></td>
              <td><%= set.name %></td>
              <td><%= set.survey_name %></td>
              <td><%= l set.created_at, format: :decidim_short %></td>
              <td class="table-list__actions">
                <%= icon_link_to "eye", Decidim::EngineRouter.main_proxy(set.component).root_url, t("actions.preview", scope: "decidim.admin"), class: "action-icon--preview" %>

                <%= icon_link_to "list", admin_indices_sat_feedbacks_path(set), t("actions.manage", scope: "decidim.admin"), class: "action-icon--edit" %>

                <%= icon_link_to "pencil", edit_admin_indices_sat_path(set), t("actions.edit", scope: "decidim.admin"), class: "action-icon--edit" %>

                <%= icon_link_to "circle-x", admin_indices_sat_path(set), t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t("actions.confirm_destroy", scope: "decidim.admin") } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate sat_list, theme: "decidim" %>
    <% else %>
      <p class="callout warning">
        No SAT sets created yet!
      </p>
    <% end %>
  </div>
</div>

app/views/decidim/admin/indices_sat/new.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      New Self-Assessment tool questionnaire
    </h2>
  </div>

  <%= decidim_form_for(@form, html: { class: "form" }, url: admin_indices_sat_index_path) do |f| %>
    <div class="card-section">
      <%= render partial: "form", object: f %>

      <div class="button--double form-general-submit">
        <%= f.submit "Send" %>
      </div>
    </div>
  <% end %>
</div>